#!/bin/bash

set -e

# we need 0666 on /dev/uhid and /dev/hidraw*

echo 'KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0666"' > /etc/udev/rules.d/00-expose-hidraw.rules
echo 'KERNEL=="uhid", SUBSYSTEM=="misc", MODE="0666"' > /etc/udev/rules.d/00-expose-uhid.rules

test ! -e /etc/rc.local || /bin/mv /etc/rc.local /etc/rc.local.backup."$(/bin/date +%Y%m%d%H%M%S)"
printf %s '#!/bin/bash
> /dev/uhid
exit 0
' > /etc/rc.local
/bin/chmod +x /etc/rc.local

# make things work without rebooting

/bin/udevadm trigger
> /dev/uhid
/bin/chmod 0666 /dev/uhid
